spring.application.name=ai-demo
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.base-url=http://langchain4j.dev/demo/openai/v1
#openaiStream
langchain4j.open-ai.streaming-chat-model.api-key=demo
langchain4j.open-ai.streaming-chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.streaming-chat-model.base-url=http://langchain4j.dev/demo/openai/v1
#dashcope
langchain4j.community.dashscope.streaming-chat-model.api-key=${QIANWEN_API_KEY}
langchain4j.community.dashscope.streaming-chat-model.model-name=qwen-plus

langchain4j.community.dashscope.chat-model.api-key=${QIANWEN_API_KEY}
langchain4j.community.dashscope.chat-model.model-name=qwen-plus

spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.uri=mongodb://localhost/test
