spring.application.name=ai-demo
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.base-url=http://langchain4j.dev/demo/openai/v1

#openaiStream
langchain4j.open-ai.streaming-chat-model.api-key=demo
langchain4j.open-ai.streaming-chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.streaming-chat-model.base-url=http://langchain4j.dev/demo/openai/v1

#dashcope
langchain4j.community.dashscope.streaming-chat-model.api-key=${QIANWEN_API_KEY}
langchain4j.community.dashscope.streaming-chat-model.model-name=qwen-plus

#embedding-model
langchain4j.community.dashscope.embedding-model.model-name=text-embedding-v1
langchain4j.community.dashscope.embedding-model.api-key=${DASH_SCOPE_API_KEY}


langchain4j.http.client.type=jdk
spring.autoconfigure.exclude=dev.langchain4j.openai.spring.AutoConfig
langchain4j.community.dashscope.chat-model.api-key=${QIANWEN_API_KEY}
langchain4j.community.dashscope.chat-model.model-name=qwen-plus

spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.uri=mongodb://localhost/test

#mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.url=jdbc:mysql://localhost:3306/skyagent?useSSL=false&allowMultiQueries=false
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-init-sql=SET SESSION TRANSACTION READ ONLY


gaode.key = ${AMAP_API_KEY}
gaode.driving-url = https://restapi.amap.com/v3/direction/

mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml

#???????
query.security.max-rows=100
security.allowed-tables=user,order,flight
security.forbidden-keywords=INSERT,UPDATE,DELETE,DROP,ALTER,CREATE,TRUNCATE,REPLACE,MERGE,RENAME


